[project]
name = "advanced-etl-project"
version = "0.1.0"
authors = [
    {name = "Kishor Kumar Paroi", email = "Kishor.ruet.cse@gmail.com"}
]
description = "Advanced ETL Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2026.7.22",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pymongo[srv]>=4.17.0",
    "python-dotenv>=1.2.2",
]
