from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add 

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description= "List of messages to be processed by the agent")
    curated_ques: str = Field(..., description="Cleaned and curated user question")
    prompt_query_text: str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    is_safe: Literal["YES", "NO"] = Field(..., description="Indicates whether the generated SQL Query is safe or not")
    generated_sql_query: str = Field(..., description="SQL query generated by the agent on the curated question and prompt context")
    sql_query_execution_result: str = Field(..., description="The result of executing the generated SQL query on the SQL Database")
    final_response: str = Field(..., description="Final answer generated by the agent on the SQL query execution result and curated question")

