from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add 

class AgentSchema(BaseModel):
    user_question: str = Field(default="", description="Original question asked by the user")
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the agent")
    curated_ques: str = Field(default="", description="Cleaned and curated user question")
    prompt_query_text: str = Field(default="", description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    is_safe: str = Field(default="", description="Indicates whether the generated SQL Query is safe or not")
    comments: str = Field(default="", description="Additional comments or feedback from the judge regarding the SQL Query")
    generated_sql_query: str = Field(default="", description="SQL query generated by the agent on the curated question and prompt context")
    sql_query_execution_result: str = Field(default="", description="The result of executing the generated SQL query on the SQL Database")
    final_response: str = Field(default="", description="Final answer generated by the agent on the SQL query execution result and curated question")

class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL Query is safe to execute or not")
    comments: str = Field(..., description="Additional comments or feedback from the judge regarding the SQL Query")