from operator import add
from typing import Annotated, Any, List, Literal
from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    """State schema for the SQL Analyst subgraph."""
    user_question: str = Field(default="", description="Original question asked by the user")
    messages: Annotated[List[Any], add] = Field(default_factory=list, description="List of messages in the workflow")
    curated_ques: str = Field(default="", description="Cleaned, refined, and unambiguous user question")
    prompt_query_text: str = Field(default="", description="Prompt with database schema context for SQL generation")
    is_safe: str = Field(default="", description="Judge decision whether the generated SQL is safe ('Yes' or 'No')")
    comments: str = Field(default="", description="Judge comments and explanation regarding SQL safety")
    generated_sql_query: str = Field(default="", description="SQL query generated by the agent")
    sql_query_execution_result: str = Field(default="", description="Result of executing the SQL query on PostgreSQL")
    final_response: str = Field(default="", description="User-friendly synthesized analytical answer")


class JudgeSchema(BaseModel):
    """Structured output schema for the SQL safety judge."""
    answer: Literal["Yes", "No"] = Field(
        ...,
        description="Whether the query is safe read-only SQL ('Yes') or unsafe DDL/DML ('No')"
    )
    comments: str = Field(..., description="Explanation of why the query is safe or unsafe")


class ETLAgentSchema(BaseModel):
    """State schema for the ETL Analyst subgraph."""
    messages: Annotated[List[Any], add] = Field(
        default_factory=list,
        description="Message history for the ETL ReAct agent"
    )


class RouterSchema(BaseModel):
    """Structured output schema for the Data Agent router."""
    answer: Literal["sql", "etl"] = Field(
        ...,
        description=(
            "Choose 'sql' if the query asks for database analytics, statistics, reports, or data from tables "
            "(rides, users, payments, vehicles, ratings, departments, employees, sales). "
            "Choose 'etl' if the query asks to fetch/extract data from external APIs/URLs, download files, "
            "transform/filter datasets, convert file formats (csv, json, parquet), or run data pipelines."
        )
    )
    comments: str = Field(..., description="Brief reasoning for routing to sql vs etl")


class DataAgentSchema(BaseModel):
    """State schema for the top-level Data Agent Supervisor."""
    messages: Annotated[List[Any], add] = Field(
        default_factory=list,
        description="Message history processed by the Data Agent"
    )
    route_response: str = Field(default="", description="Routing decision: 'sql' or 'etl'")
    final_response: str = Field(default="", description="Final synthesized response delivered to the user")