[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kishor Kumar Paroi", email = "1703053@student.ruet.ac.bd" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp",
    "qdrant-client",
    "langchain-core",
    "instructor",
    "pydantic-settings",
    "pydantic",
    "api",
]

[build-system]
requires = ["uv_build>=0.11.9,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
api = { workspace = true }
